### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by anup2050** [argonautica/redditdownloader#1]
after i start the program and put subreddit name and timestamps it does not so anything.. i attached a screenshot.. please check
![111](https://user-images.githubusercontent.com/66366537/83634119-a1cb1900-a5bf-11ea-8db7-f296cc33e380.png)

**Comment by anup2050** [comment]
it is showing number "2" instead of subreddit name in the final result which is the cause behind the error.. any suggestions how can i fix it?

**Comment by anup2050** [comment]
i tried the update today and it is not working also

**Comment by argonautica** [comment]
try using it now, it should be working.

**Comment by anup2050** [comment]
thanks.. it works now.. and its amazing.. u rockkk

**Comment by argonautica** [comment]
No problem.
